### PR TITLE
FIS Scenario OCP 3.6 Updates

### PR DESCRIPTION
**Pull request by sully6768**
The FIS Scenario has been updated with the latest screenshots from OCP 3.6. There were also updates to the instructional text to align with the new screens and workflows. Finally, there are also a number of updates to all text screens to improve readability by adding strong markdown to emphasized text.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks @sully6768

**Comment by thesteve0** [comment]
hey @sully6768 can you please include the URL for your "site" running this updated scenario. 

@mhausenblas  I think we should make that one of the requirements for "the process" - always include the URL to your version of the PR

**Comment by thesteve0** [comment]
https://katacoda.com/scottes/courses/intro-openshift/fis-deploy-app

**Comment by thesteve0** [comment]
LGTM merge when ready

**Comment by GrahamDumpleton** [comment]
Still haven't finished reviewing as got interrupted part way through.

A couple very minor differences in images between 3.4 and 3.6 not picked up, but nothing that warrants further changes at this point. They make more little tweaks in 3.7 as well so maybe pick them up when update later to 3.7.

In part 3 it says:

> This is the **follow** flog which streams the output till complete or till you hit ctrl-c.

Don't think we want ``flog`` unless it is a technical term I don't understand. ;-)

In part 3 says:

> the first of which is clicking on View Log (#3 above)

In 3.6, as seen in image used, they changed the ``View Log`` link to ``View Full Log``.

The scenario actually failed on me in the build, with:

```
I0901 03:13:33.979980       1 util.go:222] Pulling image "registry.access.redhat.com/jboss-fuse-6/fis-java-openshift@sha256:8e1e7a2c0ca13e102e39e0324303737f2812c55e89d16a59a482acc3eb2f88a1" ...
--
  | I0901 03:15:33.995285       1 docker.go:578] pulling image error : pulling image "registry.access.redhat.com/jboss-fuse-6/fis-java-openshift@sha256:8e1e7a2c0ca13e102e39e0324303737f2812c55e89d16a59a482acc3eb2f88a1" timed out after 2m0s
  | F0901 03:15:34.020155       1 helpers.go:119] error: build error: unable to get registry.access.redhat.com/jboss-fuse-6/fis-java-openshift@sha256:8e1e7a2c0ca13e102e39e0324303737f2812c55e89d16a59a482acc3eb2f88a1
```

Triggering a second build manually it worked.

Is that I saw a failure an indicator that this may or may not work sometimes for timing reasons? It may just be an issue with the test environment.

More later when finished.

**Comment by sully6768** [comment]
I fixed the page 3 errors. As for the failed build, I don't know what it might be other than a timeout or a failed pull. I haven't seen a failed build before. I have seen large delays in the startup in the test environment.

**Comment by GrahamDumpleton** [comment]
For some reason I can't see latest changes when using it out of your work area, so the following issues may not exist if you have already changed them.

In part 4 it says:

> This includes standard JVM resources such as memeory

Spelling error on 'memory'.

In part 4 it says:

> Further details on EIPs can be found at the completions of this scenario

Replace 'completions' with 'end' so reads better.

In part 4 it says:

> Once done, close the console by clicking the back link as shown below and then head back to our terminal:

This to me reads as an instruction I should do straight away so I do, ie., click on back link, but then down later I need to be on the routes again to see the numbers update. Do you really want to be telling people to click on that back link at that point, or have the image pointing out where it is? I don't see a need to as you don't want to get back to the OpenShift web console for the scenario.

Down further it says:

> Once you get back to the Hawtio console, click the Camel tab at the top and then select Route Diagram tab just below it and see if anything has changed.

but I never needed to have left the route diagram, since just above I still needed to be on there, so talking about how to get there again is probably not needed. An intermediary step just above that would have meant I had to navigate myself there anyway after I had already pressed back.

FWIW you don't need to press that back link to switch to terminal. Don't know if that is where confusion is coming from.

On summary page change link:

* http://www.openshift.org/vm

to:

* https://www.openshift.org/minishift/

The first one redirects there anyway.

Apart from that confusion in the flow with back link and where one would be in part 4, looks okay.

**Comment by thesteve0** [comment]
@sully6768 did you get to @GrahamDumpleton's fixes? I would love to merge this

**Comment by sully6768** [comment]
Sorry for the delay in responding, I was on PTO.  I will review them now and get any changes committed today.

**Comment by sully6768** [comment]
@thesteve0 and @GrahamDumpleton,

I have committed the recommended changes. The spelling issues were already completed in a prior commit so I only needed to fix the readability suggestion and the minishift web link. 

I do need to keep the one section regarding leaving the web console and then going back into it. This is a workaround for an issue that only seems to exist in the Katacoda hosted instance of FIS.  The issue is the screen which displays the message counts, for some reason, will randomly not show the updates the first time its opened up. It has to be closed and then reopened to work consistently. So I just used it as a "can you find your way back" teaching moment.

Otherwise everything else is complete.

**Pull request merged**
