### PR TITLE
Update scenarios to OpenShift 3.6.

### PR DESCRIPTION
**Pull request by GrahamDumpleton**
Can be reviewed at:

* https://host02.katacoda.com/graham.dumpleton/courses/intro-openshift

Be patient as the 3.6 test environment is on much slower hardware.

Note that this PR can only be merged at the exact same time that the production environment is switched to 3.6. IOW, don't merge unless you know you can and the change to 3.6 is being done at same time.

Check list for approval below. After at least two reviews for each, thus why two tick boxes for each.

- [x] getting-started
- [x] getting-started

- [ ] cluster-access
- [x] cluster-access

- [x] deploying-images
- [x] deploying-images

- [x] deploying-python
- [x] deploying-python

- [x] resource-objects
- [x] resource-objects

- [x] port-forwarding
- [ ] port-forwarding

- [x] transferring-files
- [ ] transferring-files

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
Comments found so far:

- Getting started with OpenShift:
  - intro page: "you will learn how to use the OpenShift Container Platform". We're using Origin. Not sure, but probably better say "OpenShift" as generic.
  - Step 2. Screenshot is from OCP.
  - Step 2. It says before the screenshot: "You should see an OpenShift Origin window"
  - Step 4. "To verify that we changed the number of replicas, click the pods number in the circle next to the arrows." If you click on the number when there is still one pod, you'll be directed to the specific pod instance page, instead of the pod listing.
  - Step 6. Not a problem, but have seen that even the build had finished, it was still shown in the overview as going on, even after the deployment had already been triggered. Would be good if others would look to see if they see this behaviour.
  - Summary: Says again OCP, and then tells about "minishift" and "oc cluster up" from origin

**Comment by jorgemoralespou** [comment]
@GrahamDumpleton Comments for the rest of the labs. I'm marking fine those without comments.
- Logging in to an OpenShift cluster:
  - Step 1: Screenshot of Origin. We should be consistent on "ocp" or "origin". Hence I would not merge until a final decision on this has ben made.
  - Step 3. Should be worth mentioning after you login on the cli as collaborator and then going to the web UI that at this point there's 2 different users and that you're logged in as one in the cli, and as the other on the web ui.
- Deploying applications from images: Only that images are from Origin.
- Deploying applications from source: Only that images are from Origin.
- Using the CLI to manage resource objects: Perfect
- Connecting to database using port forwarding:
  - Step 2: Execution of the oc new-app postgresql-ephemeral failed. I'm assuming that this is because it's using persistent templates or oc cluster up, and that don't provide the ephemeral templates.
screen shot 2017-08-21 at 11 20 49
  - Used postgresql (persistent) to test the scenario
  - Failed on Step 4 to connect to sql. Command not found:
screen shot 2017-08-21 at 11 42 48
- Transferring files in and out of containers:
  - Step 4: Failure while executing an "oc rsync" command
screen shot 2017-08-21 at 11 56 55
  - This was because $POD had two pods listed:
screen shot 2017-08-21 at 11 58 23
 I guess that the command "POD=`pod app=blog`; echo $POD" can have a race condition. If you run this command immediately after the "oc rollout status" finishes, you get 2 pods.
  - Same for Step 5.
screen shot 2017-08-21 at 12 05 59
  - And again on next change. It took a while to have the "original" pod not "Running"
screen shot 2017-08-21 at 12 07 11

**Comment by GrahamDumpleton** [comment]
The getting started scenario is a bit of a mess because we each did different parts. It has always been inconsistent in language. Some people when did it used Origin and others were using OCP on Online dev preview even though katacoda always used Origin. Have been meaning to rewrite it to be consistent, but gave up on the idea again since push was on to get 3.6 changes out ASAP. Shows why you should always have the one person do a scenario and not multiple.

Not sure why getting postgresql ephemeral deployment issues, worked perfectly last week.

The oc rsync command was also working fine last week.

The multiple pod issue is because the test environment is too slow. Not as easy to trigger on production one. Hard to do it in a way that is 100% reliable if going to have it calculate it magically as no way to sort on age of pod or anything else.

All screen images are based on Origin, even if text isn't consistent in getting started scenario, because katacoda is using Origin and that is where screen shots are taken. Argument about OCP is moot at this point as must match what katacoda is using now. Can't want for decision about OCP vs Origin.

**Comment by GrahamDumpleton** [comment]
On the missing postgresql-ephemeral, it along with image are installed from:

* https://github.com/openshift-evangelists/intro-katacoda/blob/master/intro-openshift/port-forwarding/env-init.sh

For some reason that is no longer running by katacoda on startup of instance.

If it is a general problem with that file not being run for any instance, you would expect the scenario on copying files to also fail as it relies on that file to set up volumes.

**Comment by GrahamDumpleton** [comment]
Try port forwarding again. The missing route.json file does seem to be the cause. We need to find out whether that file is even needed. It was in the very first example scenario we were given and was never clear whether was only an example or not and so whether we could remove it. Anyway, seems to cause setup to fail now when is missing.

**Comment by BenHall** [comment]
@GrahamDumpleton Sorry, I think the _route.json_ is left over from a previous way of configuring the router. When we moved to the Katacoda URLs I think the requirement for it was removed.

I can't see if referenced in the launch.sh script, so I think it's safe to be removed.

**Comment by BenHall** [comment]
The file is referenced here, which is why it's failing. https://github.com/openshift-evangelists/intro-katacoda/blob/master/intro-openshift/port-forwarding/index.json#L41-L43

I'll fix the issue on my side to ensure raises an error so you can see why a script fails to start.

**Comment by GrahamDumpleton** [comment]
Yep, was because was in index.json but not in assets directory. I will wait until after we get these 3.6 changes out before look at going through all the scenarios and dropping it.

**Pull request merged**
