### PR TITLE
Fixes for the metrics scenario

### PR DESCRIPTION
**Pull request by e-minguez**
Fixed image name

### CODE REVIEW

**Comment by e-minguez** [comment]
I've tested this in my environment a few times and now it works properly https://host02.katacoda.com/eminguez/courses/introduction/using-metrics

Do you mind to take a look? @BenHall @mhausenblas 

Once the image is ready in the production environment, I'll create a follow up PR to make it available in learn.openshift.com

Thanks folks!

**Comment by BenHall** [comment]
This is due to go live Monday/Tuesday next week

**Comment by e-minguez** [comment]
Is there something I can do to have this sooner? Thanks.

**Comment by BenHall** [comment]
We are trying to bring up the new images and infrastructure as soon as possible without causing downtime to the existing platform.

**Comment by BenHall** [comment]
This is now live

**Pull request merged**
