### PR TITLE
Update to Istio 0.6.0

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by BenHall** [comment]
FYI @jamesfalkner 

Are you OK with https://github.com/openshift-labs/learn-katacoda/blob/a05b0c99ab40a13a6657fee348d6012f192ab981/middleware/resilient-apps/assets/install-istio.sh#L3 being bumped to 0.6.0 or do we need to support both?

**Comment by BenHall** [comment]
@jamesfalkner 

I've answered by own question, after running with against the new environment I get the following errors:

```
error: services "grafana" not found
See 'oc expose -h' for help and examples.
error: services "servicegraph" not found
See 'oc expose -h' for help and examples.
route "jaeger-query" exposed
error: services "istio-ingress" not found
See 'oc expose -h' for help and examples.
error: services "prometheus" not found
See 'oc expose -h' for help and examples.
```

**Comment by BenHall** [comment]
@rafabene 
```
oc logs istio-ingress-1688831668-hkxc6
2018-03-02T12:04:45.398266Z     info    Version root@a28f609ab931-docker.io/istio-0.6.0-2cb09cdf040a8573330a127947b11e5082619895-Clean
2018-03-02T12:04:45.398323Z     info    Proxy role: model.Proxy{Type:"ingress", IPAddress:"", ID:"istio-ingress-1688831668-hkxc6.istio-system", Domain:"istio-system.svc.cluster.local"}
2018-03-02T12:04:45.398338Z     info    Attempting to lookup address: istio-mixer
2018-03-02T12:04:45.399531Z     info    Addr resolved to: 172.30.210.162:9125
2018-03-02T12:04:45.399544Z     info    Finished lookup of address: istio-mixer
2018-03-02T12:04:45.400019Z     info    Effective config: binaryPath: /usr/local/bin/envoy
configPath: /etc/istio/proxy
connectTimeout: 10.000s
discoveryAddress: istio-pilot:15003
discoveryRefreshDelay: 1.000s
drainDuration: 45.000s
parentShutdownDuration: 60.000s
proxyAdminPort: 15000
serviceCluster: istio-ingress
statsdUdpAddress: 172.30.210.162:9125
zipkinAddress: zipkin:9411

2018-03-02T12:04:45.400059Z     info    Monitored certs: []v1.CertSource{v1.CertSource{Directory:"/etc/certs/", Files:[]string{"cert-chain.pem", "key.pem", "root-cert.pem"}}, v1.CertSource{Directory:"/etc/istio/ingress-certs/", Files:[]string{"tls.crt", "tls.key"}}}
2018-03-02T12:04:45.400210Z     info    Starting proxy agent
2018-03-02T12:04:45.400339Z     info    Received new config, resetting budget
2018-03-02T12:04:45.400372Z     info    Reconciling configuration (budget 10)
2018-03-02T12:04:45.400430Z     info    Epoch 0 starting
2018-03-02T12:04:45.400912Z     error   Failed to generate bootstrap configopen /etc/istio/proxy/envoy-rev0.json: permission denied
```

**Comment by jamesfalkner** [comment]
@BenHall there are a few more changes needed to support 0.6. I'll submit a PR to get them in today.

**Comment by rafabene** [comment]
Yes. Grafana and Prometheus uses their own service-accounts now. @jamesfalkner Let me know when you have updated it so I can update the istio-tutorial

**Comment by BenHall** [comment]
@rafabene The PR from @jamesfalkner is ready #146 and is blocked by me to roll out the updated image.

**Comment by rafabene** [comment]
Thanks. I'll start updating also the istio-tutorial lab before sending the PR to learn.openshift.com

**Pull request merged**
